app:
  name: reminder

spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  sql:
    init:
      mode: always
      schema-locations: classpath:schema-${spring.profiles.active}.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password: test

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        type: trace

server:
  port: 8080