CREATE TABLE tb_user (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255) DEFAULT 'ENABLED' NOT NULL,
    name VARCHAR(255) NOT NULL,
    age SMALLINT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW() ON UPDATE NOW()
);