CREATE TABLE tb_user (
    id UNSIGNED INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255) DEFAULT 'ENABLED' NOT NULL,
    name VARCHAR(255) NOT NULL,
    age UNSIGNED SMALLINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);